modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Stalemated/s-lib_test_mod/issues"
license = "MIT"

[[mods]]
modId = "s_lib_test_mod"
version = "${version}"
displayName = "S-Lib Test Mod"
authors = "Stalemated"
description = '''
A test mod for S-Lib's config module.
'''
displayURL = "https://www.curseforge.com/minecraft/mc-mods/s-lib"

[[dependencies.s_lib_test_mod]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.s_lib_test_mod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"
